version: '2'

services:
  mq:
    image: rabbitmq:3-management

  db:
    #build: db
    image: postgres:9.4

  solr-dedup:
    build: solr-dedup

  solr-cloud1:
    build: solr-cloud

  solr-cloud2:
    build: solr-cloud

  balancer:
    build:
      context: .
      dockerfile: balancer/Dockerfile

  fetching:
    build:
      context: .
      dockerfile: fetching/Dockerfile

  extraction:
    build:
      context: .
      dockerfile: extraction/Dockerfile

  transformation:
    build:
      context: .
      dockerfile: transformation/Dockerfile

  deduplication:
    build:
      context: .
      dockerfile: deduplication/Dockerfile

  enrichment:
    build:
      context: .
      dockerfile: enrichment/Dockerfile

  enqueueing:
    build:
      context: .
      dockerfile: enqueueing/Dockerfile
    volumes:
      - "./enqueueing/app:/app:ro"
      - "./ruby-lib:/ruby-lib:ro"
    environment:
      RABBITMQ_URL: "amqp://guest:guest@mq:5672"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/enqueueing"
    depends_on:
      - db
      - mq

  index_doc_generation:
    build:
      context: .
      dockerfile: index_doc_generation/Dockerfile
    volumes:
      - "./index_doc_generation/app:/app:ro"
      - "./lib/ruby:/ruby-lib:ro"
    environment:
      RABBITMQ_URL: "amqp://guest:guest@mq:5672"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/index_docs"
    depends_on:
      - enqueueing

  indexing:
    build:
      context: .
      dockerfile: indexing/Dockerfile
    volumes:
      - "./indexing/app:/app:ro"
      - "./lib/ruby:/ruby-lib:ro"
    environment:
      RABBITMQ_URL: "amqp://guest:guest@mq:5672"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/index_docs"
      SOLR_URL: "http://solr:8983/solr"
    depends_on:
      - solr-cloud1
      - solr-cloud2
      - index_doc_generation
