version: '2'

networks:
  tupp_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/16
          gateway: 172.16.1.1

services:
  # Message queue for flow control
  mq:
    image: dtic/tupp_mq
    build: mq
    ports: 
      - "15672:15672"
      - "5672:5672"
    networks:
      tupp_net:
        ipv4_address: 172.16.1.2

  # Database
  db:
    image: dtic/tupp_db
    build: db
    networks:
      tupp_net:
        ipv4_address: 172.16.1.3

  # TUPP management interface
  management:
    build:
      context: .
      dockerfile: management/Dockerfile
    ports:
      - '3000:3000'
    networks:
      tupp_net:
        ipv4_address: 172.16.1.4
    depends_on:
      - mq
      - db

  # Stubbing service for DS2
  ds2:
    image: dtic/tupp_ds2
    build:
      context: .
      dockerfile: ds2/Dockerfile
    networks:
      - tupp_net
    environment:
      RABBITMQ_URL: 'amqp://tupp:tupp@mq:5672/%2fds2'
    depends_on:
      - mq

  harvesting:
    build:
      context: .
      dockerfile: harvesting/Dockerfile
    networks:
      - tupp_net
    environment:
      RABBITMQ_URL: 'amqp://tupp:tupp@mq:5672'
      DS_RABBITMQ_URL: 'amqp://tupp:tupp@mq:5672/%2fds2'
    depends_on:
      - mq
